### ISSUE TITLE
Known test failures 2018-02-27

### ISSUE THREAD

**Issue by sloretz** [ros2/build_farmer#87]
@ros2/team FYI these tests that are currently known to fail as of 2018-02-27. This ticket's purpose is to make it easier to judge current CI results. The failures themselves are tracked separately.

Tickets tracking failing tests
* #83 module 'enum' has no attribute 'IntFlag'
* #86 api_*_composition tests failing on some debug builds

These fail on **windows**, **osx** due to #83
```
osrf_pycommon.tests.unit.test_process_utils.test_execute_process_nopty.TestProcessUtilsExecuteNoPty.test__execute_process_nopty_combined
ros2srv.test.test_cli.test_cli
osrf_pycommon.tests.test_code_format.test_flake8
ros2pkg.test.test_cli.test_cli
ros2msg.test.test_cli.test_cli
osrf_pycommon.tests.unit.test_process_utils.test_execute_process_nopty.TestProcessUtilsExecuteNoPty.test__execute_process_nopty_combined_unbuffered
osrf_pycommon.tests.unit.test_process_utils.test_execute_process_nopty.TestProcessUtilsExecuteNoPty.test__execute_process_nopty_unbuffered
osrf_pycommon.tests.unit.test_process_utils.test_execute_process_nopty.TestProcessUtilsExecuteNoPty.test__execute_process_nopty
```

These fail on only **osx** due to #83
``` osrf_pycommon.tests.unit.test_process_utils.test_execute_process_pty.TestProcessUtilsExecuteNoPty.test__execute_process_pty_combined
osrf_pycommon.tests.unit.test_process_utils.test_execute_process_pty.TestProcessUtilsExecuteNoPty.test__execute_process_pty_unbuffered
osrf_pycommon.tests.unit.test_process_utils.test_execute_process_pty.TestProcessUtilsExecuteNoPty.test__execute_process_pty
osrf_pycommon.tests.unit.test_process_utils.test_execute_process_pty.TestProcessUtilsExecuteNoPty.test__execute_process_pty_combined_unbuffered
```

These fail only on **aarch64 debug**, **osx debug**, **windows debug** possibly #86, investigating if this warrants its own ticket.
```
projectroot.test_api_srv_composition_client_first__rmw_fastrtps_cpp
composition.test_api_srv_composition_client_first__rmw_fastrtps_cpp.xunit.missing_result
```

These fail only on **aarch64 debug** and **windows debug** #86
```
projectroot.test_api_srv_composition__rmw_fastrtps_cpp
projectroot.test_api_pubsub_composition__rmw_fastrtps_cpp
composition.test_api_srv_composition__rmw_fastrtps_cpp.xunit.missing_result
composition.test_api_pubsub_composition__rmw_fastrtps_cpp.xunit.missing_result
```
